### ISSUE TITLE
What should we do about xkbcommon?

### ISSUE THREAD

**Issue by MattBrooks95** [bradrn/wlhs#10]
I started working on the bindings for wlr_keyboard.

One of wlroots's structs is using structs defined in another library's header file.

The C code is importing xkbcommon like this
`#include <xkbcommon/xkbcommon.h>`

HSRoots was using another Haskell wrapper's library's types
[library](https://github.com/swaywm/hsroots/blob/eeacc3ff9cb9940e8a38c0d740a39242897ab059/src/Graphics/Wayland/WlRoots/Input/Keyboard.hsc#L106)
`import Text.XkbCommon.InternalTypes (CKeymap, CKeyboardState)`

So I thought about doing the same, but it doesn't build. There are error messages from xkbcommon's Setup.hs file that I don't understand. Ongy, who was working on waymonad, made a fork that apparently does build, but his fork isn't on Hackage.
https://github.com/Ongy/haskell-xkbcommon/commit/747231be338cd794d402ee720b354e3e2ac3492d
The library author pointed out that the code was very old and unmaintained https://github.com/abooij/haskell-xkbcommon/issues/9

I didn't consider situations like this because I thought we just had to wrap wlroots, but if wlroots is using C structs from other C libraries, we might have to make bindings for those too.

If we're ever going to have a nice Wayland WM written in Haskell we might need good bindings to xkbcommon too.

<details>
<summary>
My in-progress struct looks like:
</summary>
```haskell
data {-# CTYPE "wlr/types/wlr_keyboard.h" "struct wlr_keyboard_modifiers" #-} WLR_keyboard
    = WLR_keyboard
    { wlr_keyboard_base :: Ptr WLR_input_device
    , wlr_keyboard_impl :: Ptr WLR_keyboard_impl
    , wlr_keyboard_group :: Ptr WLR_keyboard_group
    , wlr_keyboard_keymap_string :: CString
    , wlr_keyboard_keymap_size :: CSize
    , wlr_keyboard_keymap_fd :: CInt
    }
    --struct xkb_keymap *keymap;
    --struct xkb_state *xkb_state;
```
</details>

<details>
<summary>
and the C struct in wlroots looks like:
</summary>
```
struct wlr_keyboard {
	struct wlr_input_device base;

	const struct wlr_keyboard_impl *impl;
	struct wlr_keyboard_group *group;

	char *keymap_string;
	size_t keymap_size;
	int keymap_fd;
	struct xkb_keymap *keymap;☆
	struct xkb_state *xkb_state;☆
	xkb_led_index_t led_indexes[WLR_LED_COUNT];☆
	xkb_mod_index_t mod_indexes[WLR_MODIFIER_COUNT];☆

	uint32_t leds;
	uint32_t keycodes[WLR_KEYBOARD_KEYS_CAP];
	size_t num_keycodes;
	struct wlr_keyboard_modifiers modifiers;

	struct {
		int32_t rate;
		int32_t delay;
	} repeat_info;

	struct {
		/**
		 * The `key` event signals with a struct wlr_keyboard_key_event that a
		 * key has been pressed or released on the keyboard. This event is
		 * emitted before the xkb state of the keyboard has been updated
		 * (including modifiers).
		 */
		struct wl_signal key;

		/**
		 * The `modifiers` event signals that the modifier state of the
		 * struct wlr_keyboard has been updated. At this time, you can read the
		 * modifier state of the struct wlr_keyboard and handle the updated
		 * state by sending it to clients.
		 */
		struct wl_signal modifiers;
		struct wl_signal keymap;
		struct wl_signal repeat_info;
	} events;

	void *data;
};

```
</details>
where some of the fields (☆) aren't defined by wlroots but are necessary to declare this struct.

**Comment by bradrn** [comment]
(It turns out I can edit your posts, so I’ve just added &lt;details&gt; tags around the big code blocks.)


If there’s already a working fork of haskell-xkbcommon, is there any reason we can’t just use that for now? A Cabal project can depend on GitHub repositories, after all. Then once we’ve gotten something working, we could look at options like taking over maintainership if necessary.

**Comment by dylan-hachmann** [comment]
We may have the same problem with [pixman](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_output.h?ref_type=heads#L83), and I don't know if there are any Haskell bindings already.

While I can't say for certain, I suspect that an older set of bindings for xkbcommon will work fine for now.

**Comment by bradrn** [comment]
> We may have the same problem with [pixman](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/include/wlr/types/wlr_output.h?ref_type=heads#L83), and I don't know if there are any Haskell bindings already.

I just double-checked wlroots, and it looks like it depends only on a very small subset of pixman structs: mostly `pixman_region32_t`, plus a few uses of `pixman_image_t`. So it should be feasible to create our own bindings to those two types if there’s no alternative.

**Comment by MattBrooks95** [comment]
I'm still stumped on what do do about xbkcommon. Ongy had a fork of it that supposedly built, but using that source didn't work, I can't get my fork to work.

haskell-xkbcommon has some template haskell that is failing in the `$ cabal build` stage. It's using a dead library called `cpphs`, and it's reading system headers like `include/linux/input.h` and indirectly including `include/sys/time.h`. It's also using some Cabal build hooks that have been removed, so I got rid of them to try and get it to compile but I'll have to substitute them with something eventually.

I made a fork trying to get it to build, but it's not going well.

If I could just write a few of the structs by hand and forego the rest of the library that would be fine, but I think our compositor will need to be able to use xkbcommon, right?

It's starting to look more and more like I need to make new bindings for libxkbcommon.

original xkbcommon bindings
https://github.com/abooij/haskell-xkbcommon
Ongy's fork of xkbcommon
https://github.com/Ongy/haskell-xkbcommon

my fork of xkbcommon where I'm poking around trying to get the TH code to compile
https://github.com/MattBrooks95/haskell-xkbcommon/blob/get-it-to-build/Text/XkbCommon/ParseDefines.hs


https://github.com/malcolmwallace/cpphs/issues/16
https://github.com/NixOS/nixpkgs/issues/63933

The xkbcommon package is broken in Nixpkgs too. I really think none of these packages have been maintained in a long time.

**Comment by bradrn** [comment]
That’s… not great news. That makes it sounds unlikely that `haskell-xkbcommon` would work.

But, on the other hand, I’m looking through `xkbcommon/xkbcommon.h` now, and at first glance it doesn’t seem all that difficult to write bindings for. Removing the (extensive) comments and blank lines, it’s only about 300 LOC. It should be doable to write bindings for that by hand, especially now that we have our convenient macros for `struct` and `enum`.

Besides, I don’t think this is such a huge problem:

> I think our compositor will need to be able to use xkbcommon, right?

It *will* need to use xkbcommon, sure… but mostly to decode whichever keysyms it’s given by wlroots, I suspect. I just searched the whole of [Sway](https://github.com/swaywm/sway), and there’s only two files which include `xkbcommon/xkbcommon.h`. And it looks like neither of them make any hugely intensive use of the library. So we might be able to get away with binding to a small subset of functions for now.

**Comment by bradrn** [comment]
Now that I think about it… what does XMonad do? After all, it must need to interface with XKB too. Perhaps I’ll look into it tomorrow.

**Comment by dylan-hachmann** [comment]
It's a bit confusing, but I think that there's a discrepancy between XKB and libxkbcommon.

From their [website](https://xkbcommon.org/doc/current/):
> While libxkbcommon's API is somewhat derived from the classic XKB API as found in `X11/extensions/XKB.h` and friends, it has been substantially reworked to expose fewer internal details to clients.

Whether or not XMonad uses bindings to XKB, I doubt it uses bindings to libxkbcommon.

**Comment by bradrn** [comment]
> Whether or not XMonad uses bindings to XKB, I doubt it uses bindings to libxkbcommon.

This seems to be right… it instead uses bindings to [X11](https://hackage.haskell.org/package/X11), which defines its own key types.

**Comment by bradrn** [comment]
Hold on, when did this get completed?

(My apologies if this is a stupid question; I’ve been working on other things and haven’t had much time to keep up with the discussions here.)
